#!/usr/bin/python2.7
# vim: set syntax=python:

from bottle import run
from gnucash import Session
from controller import AccountController

import sys

def main():
    if len(sys.argv) < 2:
        sys.stderr.write("usage: " + sys.argv[0] + " gnucash_uri [port]\n")
        exit(1)

    if len(sys.argv) > 2:
        port = int(sys.argv[2])
    else:
        port = 8080

    s = Session(sys.argv[1])
    AccountController.session = s
    try:
        run(host='localhost', port=port, debug=True)
    finally:
        s.end()

if __name__ == "__main__":
    main()
